video/urls.py
from django.urls import path
from .views import MembershipSelectView,PaymentView,updateTransactions,profile_view,cancelSubscription

app_name = 'videos'
urlpatterns = [
    path('', MembershipSelectView.as_view(), name="select" ),
    path('payment/', PaymentView, name="payment" ),
    path('update-transactions/<subscription_id>/', updateTransactions, name="update-transactions" ),
    path('profile/', profile_view, name="profile"),
    path('cancel/', cancelSubscription, name="cancel"),
]

video_sub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls', namespace="videos" )),
    path('courses/', include('courses.urls', namespace='courses')),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from video.models import Membership
from django.urls import reverse

class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    allowed_membership = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:courseDetail', kwargs={'slug': self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')


class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.CharField(max_length=200)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={
            'course_slug': self.course.slug,
            'lesson_slug': self.slug
        })

video/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
import stripe
from django.conf import settings
stripe.api_key = settings.STRIPE_SECRET_KEY
from datetime import datetime

User = get_user_model()



Membership_choices = (
    ('Enterprise', 'ent'),
    ('Professional', 'pro'),
    ('Free', 'free'),
)



class Membership(models.Model):
    slug = models.SlugField()
    membership_type = models.CharField(choices=Membership_choices,default='Free', max_length=30)
    price = models.IntegerField(default=15)
    stripe_plan_id = models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type


class UserMemberShip(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=40)
    membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    if created:
        UserMemberShip.objects.get_or_create(user=instance)

    user_membership, created = UserMemberShip.objects.get_or_create(user=instance)

    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(email=instance.email)
        user_membership.stripe_customer_id = new_customer_id['id']
        user_membership.save()

post_save.connect(post_save_usermembership_create, sender=User)

class Subscription(models.Model):
    user_membership = models.ForeignKey(UserMemberShip, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=40)
    active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user_membership.user.username


    def get_created_date(self):
       subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
       return datetime.fromtimeStamp(subscription.created)


    def get_next_billing_date(self):
        subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
        return datetime.fromtimeStamp(subscription.current_period_end)

video/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.views.generic import ListView
from .models import Membership,UserMemberShip,Subscription
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
import stripe


def profile_view(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    context = {
        'user_subscription':user_subscription,
        "user_membership":user_membership
    }
    return render(request, 'video/profile.html', context)


def get_user_membership(request):
    user_membership_qs = UserMemberShip.objects.filter(user=request.user)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None

def get_user_subscription(request):
    user_subscription_qs = Subscription.objects.filter(
        user_membership= get_user_membership(request)
    )
    if user_subscription_qs.exists():
        return user_subscription_qs.first()
        
    return None

def get_selected_membership(request):
    membership_type = request.session['selected_memebership_type']
    selected_membership_qs = Membership.objects.filter(
        membership_type = membership_type
    )
    if selected_membership_qs.exists():
        return selected_membership_qs.first()
    return None



class MembershipSelectView(LoginRequiredMixin,ListView):
    model = Membership
    template_name = 'video/membership_list.html'

    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = get_user_membership(self.request)
        context['current_membership'] = str(current_membership.membership)
        return context
    def post(self, *args,**kwargs):
        selected_membership_type  = self.request.POST.get('membership_type')
        user_membership = get_user_membership(self.request)
        user_subscription = get_user_subscription(self.request)
        selected_membership_qs = Membership.objects.filter(
            membership_type = selected_membership_type
        )
        if selected_membership_qs.exists():
            selected_membership = selected_membership_qs.first()

        # validation
        if user_membership.membership == selected_membership:
            if user_subscription != None:
                messages.info(self.request, "you already have this memebership,\
                     your  next payment is due {}".format('get this value from stripe')
                )
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        #assign to session
        self.request.session['selected_memebership_type'] = selected_membership.membership_type
        return HttpResponseRedirect(reverse('videos:payment'))


def PaymentView(request):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        try:
            # stripe.api_key = "sk_test_4fZvDGB3VzQ2OYQOyRuhq9bK00b8BiWAVb"

            token = request.POST['stripeToken']
            subscription = stripe.Subscription.create(
            customer=user_membership.stripe_customer_id,
            items=[
                {
                    "plan": selected_membership.stripe_plan_id
                    },
                ],
                source = token  #42424242424242
            )
            return redirect(reverse('videos:update-transactions',
                kwargs={
                    'subscription_id': subscription.id
                }))
        except:
            messages.info(request, "An error has occurred, investigate it in the console")
    context = {
        'publishKey': publishKey,
        'selected_membership': selected_membership
    }
    return render(request, 'video/membership_payment.html', context)


def updateTransactions(request, subscription_id):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership()
    user_membership.membership = selected_membership
    user_membership.save()
    

    sub, created = Subscription.objects.get_or_create(user_membership=user_membership)
    sub.stripe_subscription_id  = subscription_id
    sub.active = True
    sub.save()
    try:
        del request.session['selected_membership_type']
    except:
        pass

    messages.info(request, 'successfully created {} membership'.format(selected_membership))
    return redirect('/courses')


def cancelSubscription(request):
    user_sub = get_user_subscription(request)
    if user_sub.active == False:
        messages.info(request,"you don't have an active membership")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    sub  = stripe.SubScription.retrieve(user_sub.stripe_subscription_id)

    sub.delete()
    user_sub.active = False
    user_sub.save()

    free_membership = Membership.objects.filter(membership_type = 'Free').first()
    user_membership = get_user_membership(request)
    user_membership.membership = free_membership
    user_membership.save()
    messages.info(request,"successfully cancelled membership, we have sent an email")
    return redirect('/')

templates/video/membership_list.html
{% extends 'base.html'%}
    {% block content %}
    <div class="container">
        <h1 class="text-secondary">select a membership</h1>
        <div class="row bg-dark mb-4 text-white mt-3">
            {% for object in object_list %}
            <div class="col-sm-4 col-md-4">
                <hr class="my-4">
                <h2 class="text-uppercase">{{object.membership_type}}</h2>
                <hr class="my-4">
                <p>Price: ${{object.price}} <small>month</small></p>
                <h4>Included Courses:</h4>
                <ol>
                    {% for course in object.course_set.all %}
                    <li>
                        <h3 class="lead">{{course.title}}</h3>
                        <small>{{course.description}}</small>
                    </li>
                    
                    {% endfor %}
                </ol>
                {% if object.membership_type != 'Free' %}
                <form method="POST" action="{% url 'videos:select' %}" class="text-capitalize mb-5">
                    {% csrf_token %}
                    {% if object.membership_type != current_membership %}
                    <button class="btn btn-warning">select</button>
                    {%else %}
                    <small >this is your current memebership</small>
                    {% endif %}
                    <input type="hidden" name="membership_type" value="{{object.membership_type}}">
                </form>
                {% endif %}
            </div>
                
            {% endfor %}

        </div>
    </div>
    {% endblock %}

templates/video/membership_payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">
 <script src="https://js.stripe.com/v3/"></script>
 

<div class="container">
	<div class="row">
		<h1>Payment</h1>
		<div class="col-sm-6 col-md-6 col-lg-6">
			<p>Selected membership: {{ selected_membership }}</p>
      <p>Price: <strong>${{ selected_membership.price }}</strong><small>/month</small></p>
    </div>
  </div>

  <form action="." method="POST" id="payment-form">
    {% csrf_token %}
    <div class="form-row">
      <label for="card-element">
        Credit or debit card
      </label>
      <div id="card-element">
        <!-- A Stripe Element will be inserted here. -->
      </div>
  
      <!-- Used to display Element errors. -->
      <div id="card-errors" role="alert"></div>
    </div>
  
    <button>Submit Payment</button>
  </form>


  
</div>
<script src="{% static 'javascript/client.js' %}"></script>
{% endblock content %}

templates/video/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>My profile</h2>
    <div class="row text-capitalize">
        
        <div class="col-sm-4 col-md-4">
            {% if user_subscription !=  None %}
            <h4>
                Current Membership: {{user_membership.membership.membership_type}}
                <small> Since {{user_subscription.get_created_date}}</small>
                {% if user_subscription.active != False %}
                <p>Next Payment due: {{user_subscription.get_next_billing_date}}</p>
                <a href="{% url 'videos:cancel' %}">cancel Subscription</a>
                {% else %}
                <p> you dont have an active membership plan.
                    check them out here
                    <a href="{% url 'videos:select' %}">
                        <button class="btn btn-outline-warning bg-lg">select a plan</button>
                    </a>
                </p>
                {% endif %}
            </h4>
            {% else %}
            <p> you dont have an active membership plan.
                check them out here
                <a href="{% url 'videos:select' %}">
                    <button class="btn btn-outline-warning bg-lg">select a plan</button>
                </a>
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}