courses/urls.py
from django.urls import path
from .views import CourseDetailView,CourseListView,LessonDetailView

app_name = "courses"
urlpatterns = [
    path('', CourseListView.as_view(), name="courseList"),
    path('<slug>', CourseDetailView.as_view(), name="courseDetail"),
    path('<course_slug>/<lesson_slug>',LessonDetailView.as_view(), name="lesson-detail")
]

video/urls.py
from django.urls import path
from .views import MembershipSelectView,PaymentView,updateTransactions,profile_view,cancelSubscription

app_name = 'videos'
urlpatterns = [
    path('', MembershipSelectView.as_view(), name="select" ),
    path('payment/', PaymentView, name="payment" ),
    path('update-transactions/<subscription_id>/', updateTransactions, name="update-transactions" ),
    path('profile/', profile_view, name="profile"),
    path('cancel/', cancelSubscription, name="cancel"),
]

video_sub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls', namespace="videos" )),
    path('courses/', include('courses.urls', namespace='courses')),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}Video Sub{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    
    {% include 'navbar.html' %}
   <div class=" mt-5 pt-4">
    {% if messages %}
      <ul class="alert  alert-dismissible fade show" role="alert">
        {% for message in messages %}
        <li class="alert alert-{{message.tags}}" role="alert" id="alert">{{message}}</li>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {% endfor %}
      </ul>
      
   </div>
 
    {% endif %}

    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block extraScript %}
    {% endblock %}
  
  </body>
</html>

templates/navbar.html
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-danger">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" >
        <strong class="blue-text" style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Video Sub</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          
        </ul>

        <ul class="navbar-nav nav-flex-icons">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-capitalize" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              welcome {{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'courses:courseList'%}">Courses</a>
              <a class="dropdown-item" href="{% url 'videos:profile'%}">Profile</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link rounded waves-effect" href="{% url 'account_logout' %}" >
                Sign Out
            </a>
          </li> 
          {% else %}
          <li class="nav-item">
            <a  class="nav-link waves-effect"  href="{% url 'account_login' %}" >
                Sign In
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link border border-light rounded waves-effect" href="{% url 'account_signup' %}" >
                Sign Up
            </a>
          </li> 
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/profile.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "profile" %}{% endblock %}

{% block content %}
<h1>{% trans "profile" %}</h1>

<p class="lead">hi {{user.username}}</p>

{% endblock %}